let Food = [
  {
    id: 1,
    name: "Ackee, canned, drained",
    source: "Minh Cuong Tran",
    category: "vegeterian, appetizer and vegan",
    quantity: "100",
    macronutrients: {
      energy: 151,
      carbohydrate: 0.8,
      fat: 15.2,
      protein: 2.9,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 2,
    name: "Broccoli, raw",
    source: "Nutrition DB",
    category: "vegan and main course",
    quantity: "100",
    macronutrients: {
      energy: 34,
      carbohydrate: 6.6,
      fat: 0.4,
      protein: 2.8,
    },
  },
  {
    id: 3,
    name: "Apple, with skin",
    source: "Fruit Facts",
    category: "salad, dessert and breakfast",
    quantity: "100",
    macronutrients: {
      energy: 52,
      carbohydrate: 13.8,
      fat: 0.2,
      protein: 0.3,
    },
  },
  {
    id: 4,
    name: "Banana, raw",
    source: "Minh Cuong Tran",
    category: "gluten-free, dessert ,vegeterian and appetizer",
    quantity: "100",
    macronutrients: {
      energy: 89,
      carbohydrate: 22.8,
      fat: 0.3,
      protein: 1.1,
    },
  },
  {
    id: 5,
    name: "Carrot, raw",
    source: "Healthy Food DB",
    category: "low-carb, soup and breakfast",
    quantity: "100",
    macronutrients: {
      energy: 41,
      carbohydrate: 9.6,
      fat: 0.2,
      protein: 0.9,
    },
  },
  {
    id: 6,
    name: "Chicken breast, grilled",
    source: "Protein Source",
    category: "main course, gluten-free and low-carb",
    quantity: "100",
    macronutrients: {
      energy: 165,
      carbohydrate: 0,
      fat: 3.6,
      protein: 31,
    },
  },
  {
    id: 7,
    name: "Salmon, baked",
    source: "Fish Nutrition",
    category: "main course and vegeterian",
    quantity: "100",
    macronutrients: {
      energy: 206,
      carbohydrate: 0,
      fat: 12,
      protein: 22,
    },
  },
  {
    id: 8,
    name: "Brown rice, cooked",
    source: "Whole Grains DB",
    category: "low-carb, gluten-free and soup",
    quantity: "100",
    macronutrients: {
      energy: 123,
      carbohydrate: 25.6,
      fat: 1,
      protein: 2.7,
    },
  },
  {
    id: 9,
    name: "White bread",
    source: "Bakery",
    category: "dessert, breakfast and appetizer",
    quantity: "100",
    macronutrients: {
      energy: 265,
      carbohydrate: 49,
      fat: 3.2,
      protein: 9,
    },
  },
  {
    id: 10,
    name: "Egg, boiled",
    source: "Protein Source",
    category: "Animal Products",
    quantity: "100",
    macronutrients: {
      energy: 155,
      carbohydrate: 1.1,
      fat: 11,
      protein: 13,
    },
  },
  {
    id: 11,
    name: "Tofu, firm",
    source: "Vegan Base",
    category: "Vegetarian",
    quantity: "100",
    macronutrients: {
      energy: 144,
      carbohydrate: 2.3,
      fat: 8,
      protein: 15.5,
    },
  },
  {
    id: 12,
    name: "Almonds",
    source: "Nuts & Seeds",
    category: "main course",
    quantity: "100",
    macronutrients: {
      energy: 579,
      carbohydrate: 21.6,
      fat: 49.9,
      protein: 21.2,
    },
  },
  {
    id: 13,
    name: "Cheddar cheese",
    source: "Dairy Base",
    category: "salad",
    quantity: "100",
    macronutrients: {
      energy: 403,
      carbohydrate: 1.3,
      fat: 33,
      protein: 25,
    },
  },
  {
    id: 14,
    name: "Greek yogurt, plain",
    source: "Dairy Base",
    category: "vegan",
    quantity: "100",
    macronutrients: {
      energy: 59,
      carbohydrate: 3.6,
      fat: 0.4,
      protein: 10,
    },
  },
  {
    id: 15,
    name: "Lentils, boiled",
    source: "Plant Protein",
    category: "soup and breakfast",
    quantity: "100",
    macronutrients: {
      energy: 116,
      carbohydrate: 20.1,
      fat: 0.4,
      protein: 9,
    },
  },
  {
    id: 16,
    name: "Sweet potato, baked",
    source: "Root Veggies",
    category: "gluten-free and breakfast",
    quantity: "100",
    macronutrients: {
      energy: 90,
      carbohydrate: 20.7,
      fat: 0.1,
      protein: 2,
    },
  },
  {
    id: 17,
    name: "Avocado",
    source: "Healthy Fats",
    category: "main course and dessert",
    quantity: "100",
    macronutrients: {
      energy: 160,
      carbohydrate: 8.5,
      fat: 14.7,
      protein: 2,
    },
  },
  {
    id: 18,
    name: "Beef, ground, cooked",
    source: "Meat",
    category: "breakfast and vegeterian",
    quantity: "100",
    macronutrients: {
      energy: 250,
      carbohydrate: 0,
      fat: 15,
      protein: 26,
    },
  },
  {
    id: 19,
    name: "Shrimp, cooked",
    source: "Fish",
    category: "dessert and gluten-free",
    quantity: "100",
    macronutrients: {
      energy: 99,
      carbohydrate: 0.2,
      fat: 0.3,
      protein: 24,
    },
  },
  {
    id: 20,
    name: "Pumpkin, cooked",
    source: "Vegetable Base",
    category: "vegeterian and soup",
    quantity: "100",
    macronutrients: {
      energy: 26,
      carbohydrate: 6.5,
      fat: 0.1,
      protein: 1,
    },
  },
  {
    id: 21,
    name: "Mango, raw",
    source: "Fruits",
    category: "main course and ow-carb",
    quantity: "100",
    macronutrients: {
      energy: 60,
      carbohydrate: 15,
      fat: 0.4,
      protein: 0.8,
    },
  },
  {
    id: 22,
    name: "Almonds, raw",
    source: "Minh Cuong Tran",
    category: "dessert and appetizer",
    quantity: "100",
    macronutrients: {
      energy: 579,
      carbohydrate: 21.6,
      fat: 49.9,
      protein: 21.2,
    },
  },
  {
    id: 23,
    name: "Apple, raw",
    source: "Minh Cuong Tran",
    category: "gluten-free and breakfast",
    quantity: "100",
    macronutrients: {
      energy: 52,
      carbohydrate: 13.8,
      fat: 0.2,
      protein: 0.3,
    },
  },
  {
    id: 24,
    name: "Avocado, raw",
    source: "Minh Cuong Tran",
    category: "salad and soup",
    quantity: "100",
    macronutrients: {
      energy: 160,
      carbohydrate: 8.5,
      fat: 14.7,
      protein: 2,
    },
  },
  {
    id: 25,
    name: "Banana, raw",
    source: "Minh Cuong Tran",
    category: "dessert",
    quantity: "100",
    macronutrients: {
      energy: 89,
      carbohydrate: 22.8,
      fat: 0.3,
      protein: 1.1,
    },
  },
  {
    id: 26,
    name: "Beef, cooked",
    source: "Minh Cuong Tran",
    category: "main course",
    quantity: "100",
    macronutrients: {
      energy: 250,
      carbohydrate: 0,
      fat: 15.4,
      protein: 26.1,
    },
  },
  {
    id: 27,
    name: "Broccoli, raw",
    source: "Minh Cuong Tran",
    category: "appetizer",
    quantity: "100",
    macronutrients: {
      energy: 34,
      carbohydrate: 6.6,
      fat: 0.4,
      protein: 2.8,
    },
  },
  {
    id: 28,
    name: "Carrot, raw",
    source: "Minh Cuong Tran",
    category: "vegeterian",
    quantity: "100",
    macronutrients: {
      energy: 41,
      carbohydrate: 9.6,
      fat: 0.2,
      protein: 0.9,
    },
  },
  {
    id: 29,
    name: "Chicken breast, cooked",
    source: "Minh Cuong Tran",
    category: "main course and gluten-free",
    quantity: "100",
    macronutrients: {
      energy: 165,
      carbohydrate: 0,
      fat: 3.6,
      protein: 31,
    },
  },
  {
    id: 30,
    name: "Chickpeas, cooked",
    source: "Minh Cuong Tran",
    category: "breakfast",
    quantity: "100",
    macronutrients: {
      energy: 164,
      carbohydrate: 27.4,
      fat: 2.6,
      protein: 8.9,
    },
  },
  {
    id: 31,
    name: "Cucumber, raw",
    source: "Minh Cuong Tran",
    category: "appetizer and vegan",
    quantity: "100",
    macronutrients: {
      energy: 16,
      carbohydrate: 3.6,
      fat: 0.1,
      protein: 0.7,
    },
  },
  {
    id: 32,
    name: "Egg, whole, raw",
    source: "Minh Cuong Tran",
    category: "main course, low-carb and gluten-free",
    quantity: "100",
    macronutrients: {
      energy: 143,
      carbohydrate: 0.7,
      fat: 9.5,
      protein: 12.6,
    },
  },
  {
    id: 33,
    name: "Garlic, raw",
    source: "Minh Cuong Tran",
    category: "gluten-free, breakfast and vegeterian",
    quantity: "100",
    macronutrients: {
      energy: 149,
      carbohydrate: 33.1,
      fat: 0.5,
      protein: 6.4,
    },
  },
  {
    id: 34,
    name: "Greek yogurt, plain",
    source: "Minh Cuong Tran",
    category: "dessert, salad and low-carb",
    quantity: "100",
    macronutrients: {
      energy: 59,
      carbohydrate: 3.6,
      fat: 0.4,
      protein: 10,
    },
  },
  {
    id: 35,
    name: "Kale, raw",
    source: "Minh Cuong Tran",
    category: "vegeterian and appetizer",
    quantity: "100",
    macronutrients: {
      energy: 49,
      carbohydrate: 8.8,
      fat: 0.9,
      protein: 4.3,
    },
  },
  {
    id: 36,
    name: "Lentils, cooked",
    source: "Minh Cuong Tran",
    category: "gluten-free, appetizer and soup",
    quantity: "100",
    macronutrients: {
      energy: 116,
      carbohydrate: 20.1,
      fat: 0.4,
      protein: 9,
    },
  },
  {
    id: 37,
    name: "Lettuce, raw",
    source: "Minh Cuong Tran",
    category: "vegeterian, appetizer and dessert",
    quantity: "100",
    macronutrients: {
      energy: 15,
      carbohydrate: 3.1,
      fat: 0.2,
      protein: 1.4,
    },
  },
  {
    id: 38,
    name: "Mango, raw",
    source: "Minh Cuong Tran",
    category: "dessert and salad",
    quantity: "100",
    macronutrients: {
      energy: 60,
      carbohydrate: 15,
      fat: 0.4,
      protein: 0.8,
    },
  },
  {
    id: 39,
    name: "Oats, raw",
    source: "Minh Cuong Tran",
    category: "dessert, vegeterian and low-carb",
    quantity: "100",
    macronutrients: {
      energy: 389,
      carbohydrate: 66.3,
      fat: 6.9,
      protein: 16.9,
    },
  },
  {
    id: 40,
    name: "Orange, raw",
    source: "Minh Cuong Tran",
    category: "salad and appetizer",
    quantity: "100",
    macronutrients: {
      energy: 47,
      carbohydrate: 11.8,
      fat: 0.1,
      protein: 0.9,
    },
  },
  {
    id: 41,
    name: "Salmon, cooked",
    source: "Minh Cuong Tran",
    category: "gluten-free, vegan and vegeterian",
    quantity: "100",
    macronutrients: {
      energy: 208,
      carbohydrate: 0,
      fat: 13.4,
      protein: 20.4,
    },
  },
];


