let Food = [
  {
    id: 1,
    name: "Ackee, canned, drained",
    source: "Minh Cuong Tran",
    category: "",
    quantity: "100",
    macronutrients: {
      energy: 151,
      carbohydrate: 0.8,
      fat: 15.2,
      protein: 2.9,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 2,
    name: "Broccoli, raw",
    source: "Nutrition DB",
    category: "vegan and main course",
    quantity: "100",
    macronutrients: {
      energy: 34,
      carbohydrate: 6.6,
      fat: 0.4,
      protein: 2.8,
    },
    micronutrients: {
      cholesterol: 78.2,
      fiber: null,
      sodium: null,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: null,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: 3.24,
      vitaminK: null,
      starch: 0.0,
      lactose: 40.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: 55.6,
      selenium: 24.6,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: 6.43,
      fattyAcidsMonounsaturated: 45,
      fattyAcidsPolyunsaturated: 0.08,
      chloride: 41.3,
    },
  },
  {
    id: 3,
    name: "Apple, with skin",
    source: "Fruit Facts",
    category: "salad, dessert and breakfast",
    quantity: "100",
    macronutrients: {
      energy: 52,
      carbohydrate: 13.8,
      fat: 0.2,
      protein: 0.3,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 20.90,
      water: 76.7,
      vitaminA: 6.7,
      vitaminB6: 3.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: 35,
      vitaminK: null,
      starch: null,
      lactose: null,
      alcohol:4.3,
      caffeine:0.08,
      sugars:5.22,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 0.70,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: 46.3,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: 5.34,
      fattyAcidsPolyunsaturated: 78,
      chloride: 140.0,
    },
  },
  {
    id: 4,
    name: "Banana, raw",
    source: "Minh Cuong Tran",
    category: "gluten-free, dessert ,vegeterian and appetizer",
    quantity: "100",
    macronutrients: {
      energy: 89,
      carbohydrate: 22.8,
      fat: 0.3,
      protein: 1.1,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: 24.5,
      vitaminK: null,
      starch: 0.04,
      lactose: null,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 76.05,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: 35.3,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: 6.3,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.203,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: 24.5,
      fattyAcidsPolyunsaturated: 0.56,
      chloride: 50.0,
    },
  },
  {
    id: 5,
    name: "Carrot, raw",
    source: "Healthy Food DB",
    category: "low-carb, soup and breakfast",
    quantity: "100",
    macronutrients: {
      energy: 41,
      carbohydrate: 9.6,
      fat: 0.2,
      protein: 0.9,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 6,
    name: "Chicken breast, grilled",
    source: "Protein Source",
    category: "main course, gluten-free and low-carb",
    quantity: "100",
    macronutrients: {
      energy: 165,
      carbohydrate: 0,
      fat: 3.6,
      protein: 31,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 7,
    name: "Salmon, baked",
    source: "Fish Nutrition",
    category: "main course and vegeterian",
    quantity: "100",
    macronutrients: {
      energy: 206,
      carbohydrate: 0,
      fat: 12,
      protein: 22,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 8,
    name: "Brown rice, cooked",
    source: "Whole Grains DB",
    category: "low-carb, gluten-free and soup",
    quantity: "100",
    macronutrients: {
      energy: 123,
      carbohydrate: 25.6,
      fat: 1,
      protein: 2.7,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 9,
    name: "White bread",
    source: "Bakery",
    category: "dessert, breakfast and appetizer",
    quantity: "100",
    macronutrients: {
      energy: 265,
      carbohydrate: 49,
      fat: 3.2,
      protein: 9,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 10,
    name: "Egg, boiled",
    source: "Protein Source",
    category: "Animal Products",
    quantity: "100",
    macronutrients: {
      energy: 155,
      carbohydrate: 1.1,
      fat: 11,
      protein: 13,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 11,
    name: "Tofu, firm",
    source: "Vegan Base",
    category: "Vegetarian",
    quantity: "100",
    macronutrients: {
      energy: 144,
      carbohydrate: 2.3,
      fat: 8,
      protein: 15.5,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 12,
    name: "Almonds",
    source: "Nuts & Seeds",
    category: "main course",
    quantity: "100",
    macronutrients: {
      energy: 579,
      carbohydrate: 21.6,
      fat: 49.9,
      protein: 21.2,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 13,
    name: "Cheddar cheese",
    source: "Dairy Base",
    category: "salad",
    quantity: "100",
    macronutrients: {
      energy: 403,
      carbohydrate: 1.3,
      fat: 33,
      protein: 25,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 14,
    name: "Greek yogurt, plain",
    source: "Dairy Base",
    category: "vegan",
    quantity: "100",
    macronutrients: {
      energy: 59,
      carbohydrate: 3.6,
      fat: 0.4,
      protein: 10,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 15,
    name: "Lentils, boiled",
    source: "Plant Protein",
    category: "soup and breakfast",
    quantity: "100",
    macronutrients: {
      energy: 116,
      carbohydrate: 20.1,
      fat: 0.4,
      protein: 9,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 16,
    name: "Sweet potato, baked",
    source: "Root Veggies",
    category: "gluten-free and breakfast",
    quantity: "100",
    macronutrients: {
      energy: 90,
      carbohydrate: 20.7,
      fat: 0.1,
      protein: 2,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 17,
    name: "Avocado",
    source: "Healthy Fats",
    category: "main course and dessert",
    quantity: "100",
    macronutrients: {
      energy: 160,
      carbohydrate: 8.5,
      fat: 14.7,
      protein: 2,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 18,
    name: "Beef, ground, cooked",
    source: "Meat",
    category: "breakfast and vegeterian",
    quantity: "100",
    macronutrients: {
      energy: 250,
      carbohydrate: 0,
      fat: 15,
      protein: 26,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 19,
    name: "Shrimp, cooked",
    source: "Fish",
    category: "dessert and gluten-free",
    quantity: "100",
    macronutrients: {
      energy: 99,
      carbohydrate: 0.2,
      fat: 0.3,
      protein: 24,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 20,
    name: "Pumpkin, cooked",
    source: "Vegetable Base",
    category: "vegeterian and soup",
    quantity: "100",
    macronutrients: {
      energy: 26,
      carbohydrate: 6.5,
      fat: 0.1,
      protein: 1,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 21,
    name: "Mango, raw",
    source: "Fruits",
    category: "main course and ow-carb",
    quantity: "100",
    macronutrients: {
      energy: 60,
      carbohydrate: 15,
      fat: 0.4,
      protein: 0.8,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 22,
    name: "Almonds, raw",
    source: "Minh Cuong Tran",
    category: "dessert and appetizer",
    quantity: "100",
    macronutrients: {
      energy: 579,
      carbohydrate: 21.6,
      fat: 49.9,
      protein: 21.2,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 23,
    name: "Apple, raw",
    source: "Minh Cuong Tran",
    category: "gluten-free and breakfast",
    quantity: "100",
    macronutrients: {
      energy: 52,
      carbohydrate: 13.8,
      fat: 0.2,
      protein: 0.3,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 24,
    name: "Avocado, raw",
    source: "Minh Cuong Tran",
    category: "salad and soup",
    quantity: "100",
    macronutrients: {
      energy: 160,
      carbohydrate: 8.5,
      fat: 14.7,
      protein: 2,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 25,
    name: "Banana, raw",
    source: "Minh Cuong Tran",
    category: "dessert",
    quantity: "100",
    macronutrients: {
      energy: 89,
      carbohydrate: 22.8,
      fat: 0.3,
      protein: 1.1,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 26,
    name: "Beef, cooked",
    source: "Minh Cuong Tran",
    category: "main course",
    quantity: "100",
    macronutrients: {
      energy: 250,
      carbohydrate: 0,
      fat: 15.4,
      protein: 26.1,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 27,
    name: "Broccoli, raw",
    source: "Minh Cuong Tran",
    category: "appetizer",
    quantity: "100",
    macronutrients: {
      energy: 34,
      carbohydrate: 6.6,
      fat: 0.4,
      protein: 2.8,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 28,
    name: "Carrot, raw",
    source: "Minh Cuong Tran",
    category: "vegeterian",
    quantity: "100",
    macronutrients: {
      energy: 41,
      carbohydrate: 9.6,
      fat: 0.2,
      protein: 0.9,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 29,
    name: "Chicken breast, cooked",
    source: "Minh Cuong Tran",
    category: "main course and gluten-free",
    quantity: "100",
    macronutrients: {
      energy: 165,
      carbohydrate: 0,
      fat: 3.6,
      protein: 31,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 30,
    name: "Chickpeas, cooked",
    source: "Minh Cuong Tran",
    category: "breakfast",
    quantity: "100",
    macronutrients: {
      energy: 164,
      carbohydrate: 27.4,
      fat: 2.6,
      protein: 8.9,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 31,
    name: "Cucumber, raw",
    source: "Minh Cuong Tran",
    category: "appetizer and vegan",
    quantity: "100",
    macronutrients: {
      energy: 16,
      carbohydrate: 3.6,
      fat: 0.1,
      protein: 0.7,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 60.45,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: null,
      vitaminE: null,
      vitaminK: 6.35,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: 5.36,
      selenium: 0.65,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: 5,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: 462,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 32,
    name: "Egg, whole, raw",
    source: "Minh Cuong Tran",
    category: "main course, low-carb and gluten-free",
    quantity: "100",
    macronutrients: {
      energy: 143,
      carbohydrate: 0.7,
      fat: 9.5,
      protein: 12.6,
    },
    micronutrients: {
      cholesterol: null,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 40.03,
      vitaminC: 30.0,
      vitaminD: 20.30,
      vitaminE: null,
      vitaminK: 46,
      starch: 0.02,
      lactose: null,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: 45,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: 68,
      fattyAcidsPolyunsaturated: 45.6,
      chloride: 340.0,
    },
  },
  {
    id: 33,
    name: "Garlic, raw",
    source: "Minh Cuong Tran",
    category: "gluten-free, breakfast and vegeterian",
    quantity: "100",
    macronutrients: {
      energy: 149,
      carbohydrate: 33.1,
      fat: 0.5,
      protein: 6.4,
    },
    micronutrients: {
      cholesterol: 5.0,
      fiber: null,
      sodium: 230.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: 56,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.37,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: 5.3,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: 4,
      chloride: 52.0,
    },
  },
  {
    id: 34,
    name: "Greek yogurt, plain",
    source: "Minh Cuong Tran",
    category: "dessert, salad and low-carb",
    quantity: "100",
    macronutrients: {
      energy: 59,
      carbohydrate: 3.6,
      fat: 0.4,
      protein: 10,
    },
    micronutrients: {
      cholesterol: 7.08,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: 67.34,
      starch: 30.40,
      lactose: 0.03,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.20,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 262.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 12.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 104.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: 345.2,
      fattyAcidsPolyunsaturated: 3.09,
      chloride: 340.0,
    },
  },
  {
    id: 35,
    name: "Kale, raw",
    source: "Minh Cuong Tran",
    category: "vegeterian and appetizer",
    quantity: "100",
    macronutrients: {
      energy: 49,
      carbohydrate: 8.8,
      fat: 0.9,
      protein: 4.3,
    },
    micronutrients: {
      cholesterol: 45.0,
      fiber: null,
      sodium: 70.7,
      water: 26.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: 34,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:10.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 70.80,
      zinc: 0.6,
      copper: 0.27,
      fluoride: 56,
      manganese: null,
      selenium: 45,
      thiamin: 0.03,
      riboflavin: 1.07,
      niacin: 10.6,
      pantothenicAcid: 12.56,
      folateTotal: null,
      folicAcid: null,
      fattyAcidsTrans: 0.04,
      fattyAcidsSaturated: 0.24,
      fattyAcidsMonounsaturated: 5.22,
      fattyAcidsPolyunsaturated: 34.2,
      chloride: null,
    },
  },
  {
    id: 36,
    name: "Lentils, cooked",
    source: "Minh Cuong Tran",
    category: "gluten-free, appetizer and soup",
    quantity: "100",
    macronutrients: {
      energy: 116,
      carbohydrate: 20.1,
      fat: 0.4,
      protein: 9,
    },
    micronutrients: {
      cholesterol: 30.0,
      fiber: null,
      sodium: 24.40,
      water: 78.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 34.2,
      vitaminC: 3.09,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: 12,
      starch: 0.0,
      lactose: null,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 51.56,
      zinc: 0.6,
      copper: 0.27,
      fluoride: 0.06,
      manganese: null,
      selenium: 34,
      thiamin: 0.03,
      riboflavin: 4.27,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: 19.75,
      fattyAcidsPolyunsaturated: 0.94,
      chloride: 0.0,
    },
  },
  {
    id: 37,
    name: "Lettuce, raw",
    source: "Minh Cuong Tran",
    category: "vegeterian, appetizer and dessert",
    quantity: "100",
    macronutrients: {
      energy: 15,
      carbohydrate: 3.1,
      fat: 0.2,
      protein: 1.4,
    },
    micronutrients: {
      cholesterol: 5.01,
      fiber: null,
      sodium: null,
      water: 7.7,
      vitaminA: 9.05,
      vitaminB6: 0.06,
      vitaminB12: 12,
      vitaminC: 36.0,
      vitaminD: 0.34,
      vitaminE: 56,
      vitaminK: 0.98,
      starch: null,
      lactose: null,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 450.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: 23,
      manganese: null,
      selenium: 0.5,
      thiamin: 10.3,
      riboflavin: 7.07,
      niacin: 0.6,
      pantothenicAcid: 45,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: 12.5,
      fattyAcidsMonounsaturated: 34.5,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 38,
    name: "Mango, raw",
    source: "Minh Cuong Tran",
    category: "dessert and salad",
    quantity: "100",
    macronutrients: {
      energy: 60,
      carbohydrate: 15,
      fat: 0.4,
      protein: 0.8,
    },
    micronutrients: {
      cholesterol: 0.0,
      fiber: null,
      sodium: 240.0,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 0.0,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 270.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 39,
    name: "Oats, raw",
    source: "Minh Cuong Tran",
    category: "dessert, vegeterian and low-carb",
    quantity: "100",
    macronutrients: {
      energy: 389,
      carbohydrate: 66.3,
      fat: 6.9,
      protein: 16.9,
    },
    micronutrients: {
      cholesterol: 0.07,
      fiber: null,
      sodium: 50.03,
      water: 76.7,
      vitaminA: 56,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: null,
      vitaminE: null,
      vitaminK: 34,
      starch: 5.0,
      lactose: 0.9,
      alcohol:4.32,
      caffeine:0.08,
      sugars:null,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 40.0,
      phosphorus: 47.0,
      potassium: 120.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: null,
      selenium: 12.56,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: null,
      folateTotal: 41.0,
      folicAcid: null,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: null,
      fattyAcidsMonounsaturated: 6.78,
      fattyAcidsPolyunsaturated: null,
      chloride: 340.0,
    },
  },
  {
    id: 40,
    name: "Orange, raw",
    source: "Minh Cuong Tran",
    category: "salad and appetizer",
    quantity: "100",
    macronutrients: {
      energy: 47,
      carbohydrate: 11.8,
      fat: 0.1,
      protein: 0.9,
    },
    micronutrients: {
      cholesterol: null,
      fiber: 67,
      sodium: 120.04,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: null,
      vitaminE: null,
      vitaminK: null,
      starch: 0.0,
      lactose: 0.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:null,
      calcium: 95.0,
      iron: 0.77,
      magnesium: 40.03,
      phosphorus: 87.0,
      potassium: 20.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: 45,
      selenium: null,
      thiamin: 10.03,
      riboflavin: 0.17,
      niacin: 0.6,
      pantothenicAcid: 24.3,
      folateTotal: null,
      folicAcid: null,
      fattyAcidsTrans: 0.06,
      fattyAcidsSaturated: 4.24,
      fattyAcidsMonounsaturated: 0.46,
      fattyAcidsPolyunsaturated: 12.5,
      chloride: null,
    },
  },
  {
    id: 41,
    name: "Salmon, cooked",
    source: "Minh Cuong Tran",
    category: "gluten-free, vegan and vegeterian",
    quantity: "100",
    macronutrients: {
      energy: 208,
      carbohydrate: 0,
      fat: 13.4,
      protein: 20.4,
    },
    micronutrients: {
      cholesterol: 20.02,
      fiber: 24,
      sodium: null,
      water: 76.7,
      vitaminA: null,
      vitaminB6: 0.06,
      vitaminB12: 0.0,
      vitaminC: 30.0,
      vitaminD: 2.45,
      vitaminE: null,
      vitaminK: 5.67,
      starch: null,
      lactose: 10.0,
      alcohol:4.3,
      caffeine:0.08,
      sugars:34,
      calcium: 35.0,
      iron: 0.7,
      magnesium: 18.0,
      phosphorus: 47.0,
      potassium: 225.0,
      zinc: 0.6,
      copper: 0.27,
      fluoride: null,
      manganese: 78.87,
      selenium: null,
      thiamin: 0.03,
      riboflavin: 0.07,
      niacin: 0.6,
      pantothenicAcid: 41.0,
      folateTotal: null,
      folicAcid: 45,
      fattyAcidsTrans: 0.0,
      fattyAcidsSaturated: 12.5,
      fattyAcidsMonounsaturated: null,
      fattyAcidsPolyunsaturated: null,
      chloride: 34.50,
    },
  },
];


